modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/Bawnorton/BetterTrims/issues"
license = "MIT"

[[mods]]
modId = "bettertrims"
version = "${version}"
displayName = "BetterTrims"
authors = "Bawnorton"
description = '''
${description}
'''
logoFile = "assets/bettertrims/icon.png"

[[mixins]]
config = "bettertrims.mixins.json"

[[mixins]]
config = "bettertrims-client.mixins.json"

[[dependencies.bettertrims]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettertrims]]
modId = "configurable"
type = "required"
versionRange = ">=1.3.0"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettertrims]]
modId = "fabric_api"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettertrims]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = ">=3.5.0"
ordering = "NONE"
side = "BOTH"